set -g prefix C-t

# setw -g utf-8 on
set -g history-limit 10000
set -gw mode-keys vi
set -s escape-time 0
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g automatic-rename on
set -g mouse on
set -g status-interval 1
bind | split-window -h
bind - split-window -v
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-left-length 50
set -g status-left "#[fg=green,bg=white][#S]#[default] "
set -g window-status-format "#[fg=black,bg=green]#I:#W #[default]"
set -g window-status-current-format "#[fg=white,bold,bg=green]#I:#W #[default]"
set -g status-right-length 120
set -g status-right "#{p-28:#{?client_prefix,#[reverse] PREFIX #[default],}#{?#{m:copy-mode*,#{pane_mode}},#[reverse] COPY #[default],}#{?pane_synchronized,#[reverse] SYNC #[default],}#{?window_zoomed_flag,#[reverse] ZOOM #[default],}}  #H  %m/%d(%a) %H:%M:%S"
