alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vimrc"
alias ohmyzsh="cd ~/.oh-my-zsh"
alias tempenv="tmpenv"
alias budug="brew update && brew upgrade"
alias aliases="vim ~/.oh-my-zsh/custom/aliases.zsh"
